theme: jekyll-theme-cayman
title: DNN Sharp Documentation Center 
github: [metadata]

email: support@dnnsharp.com
description: >- # this means to ignore newlines until "baseurl:"
  The brand new site that hosts the DnnSharp Product Documentation.<br />
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://docs.dnnsharp.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username: dnnsharp

# Build settings
markdown: kramdown
plugins:
  - octopress-debugger
  - jekyll-sitemap
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .history/